version: '3.9'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./app:/var/www/symfony
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx:/etc/nginx/templates/
      - ./app:/var/www/symfony
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      DOMAIN: ${DOMAIN}
      NGINX_PORT: ${NGINX_PORT}
      APP_ENV: ${APP_ENV}
    depends_on:
      - php

  sphinx:
    image: manticoresearch/manticore:latest
    container_name: sphinx
    restart: always
    environment:
      - EXTRA=1
      - CREATE_PLAIN_TABLES=idx_orders;idx_orders:* * * * *;
    ports:
      - "9306:9306"
      - "9312:9312"
      - "9306:9306"
      - "9308:9308"
    volumes:
      - ./sphinx/manticore.conf:/etc/manticoresearch/manticore.conf # uncomment if you use a custom config
      - ./sphinx/data:/var/lib/manticore  # Обеспечивает сохранение индекса
    depends_on:
      - php
volumes:
  mysql_data:


